/**
 * Реестр редактируемых текстов сайта.
 *
 * Значение по умолчанию живёт здесь, изменённое лежит в таблице SiteText.
 * Ключи не переименовывать: по ним хранятся правки администрации.
 */

export type TextGroup =
  | 'nav'
  | 'home'
  | 'posts'
  | 'post'
  | 'postForm'
  | 'votes'
  | 'players'
  | 'player'
  | 'me'
  | 'login'
  | 'archive'
  | 'media'
  | 'wiki'
  | 'map'
  | 'points'
  | 'about'
  | 'zero'
  | 'join'
  | 'corner'
  | 'team'
  | 'notfound'
  | 'footer';

export type TextEntry = {
  /** название поля в админке */
  label: string;
  /** где этот текст виден на сайте */
  hint: string;
  group: TextGroup;
  value: string;
  maxLength: number;
  multiline?: boolean;
};

export const TEXT_GROUPS: Record<TextGroup, string> = {
  nav: 'Меню и шапка',
  home: 'Главная',
  posts: 'Лента завозов',
  post: 'Карточка и страница завоза',
  postForm: 'Новый завоз и правка',
  votes: 'Голосование',
  players: 'Игроки',
  player: 'Страница игрока',
  me: 'Личный кабинет',
  login: 'Вход',
  archive: 'Архив',
  media: 'Медиа',
  wiki: 'Вики',
  map: 'Карта',
  points: 'Баллы',
  about: 'Что такое KRUG',
  zero: 'Zero Season',
  join: 'Как попасть',
  corner: 'Угол',
  team: 'Команда',
  notfound: 'Страница 404',
  footer: 'Подвал',
};

export const SITE_TEXTS: Record<string, TextEntry> = {
  'hero.title': {
    label: 'Заголовок первого экрана',
    hint: 'Крупная надпись на главной. Звёздочки делают слово зелёным: Создаём круг там, где *квадрат*',
    group: 'home',
    value: 'Создаём круг там,\nгде *квадрат*',
    maxLength: 120,
    multiline: true,
  },
  'hero.lead': {
    label: 'Подзаголовок первого экрана',
    hint: 'Абзац под заголовком главной',
    group: 'home',
    value:
      'KRUG: приватный сервер Minecraft Java Edition 26.2. Небольшой состав, общая история и архив, куда попадает каждая неделя. Мы тут без *острых углов*.',
    maxLength: 400,
    multiline: true,
  },
  'hero.status.label': {
    label: 'Подпись над статусом',
    hint: 'Мелкая надпись в панели статуса проекта',
    group: 'home',
    value: 'Статус проекта',
    maxLength: 60,
  },
  'hero.button.login': {
    label: 'Кнопка входа',
    hint: 'Первый экран, кнопка с текстурой',
    group: 'home',
    value: 'Войти',
    maxLength: 40,
  },
  'hero.button.join': {
    label: 'Кнопка «Как попасть»',
    hint: 'Первый экран, вторая кнопка для гостей',
    group: 'home',
    value: 'Как попасть',
    maxLength: 40,
  },
  'hero.button.zero': {
    label: 'Кнопка Zero Season',
    hint: 'Первый экран, третья кнопка',
    group: 'home',
    value: 'Zero Season',
    maxLength: 40,
  },
  'hero.button.posts': {
    label: 'Кнопка для вошедших',
    hint: 'Первый экран, показывается вместо входа',
    group: 'home',
    value: 'Смотреть завозы',
    maxLength: 40,
  },

  'section.trailer': {
    label: 'Заголовок секции с трейлером',
    hint: 'Главная, левая колонка. Пусто означает подпись из настроек трейлера',
    group: 'home',
    value: '',
    maxLength: 80,
  },
  'section.week': {
    label: 'Заголовок секции архива недели',
    hint: 'Главная, правая колонка',
    group: 'home',
    value: 'Архив недели',
    maxLength: 80,
  },
  'section.top': {
    label: 'Заголовок секции с топом',
    hint: 'Главная, блок с лучшими авторами недели',
    group: 'home',
    value: 'Завозчики недели',
    maxLength: 80,
  },
  'section.posts': {
    label: 'Заголовок секции с лентой',
    hint: 'Главная, блок последних завозов',
    group: 'home',
    value: 'Последние завозы',
    maxLength: 80,
  },
  'about.card.title': {
    label: 'Заголовок карточки о проекте',
    hint: 'Главная, нижний блок слева',
    group: 'home',
    value: 'Что такое KRUG',
    maxLength: 80,
  },
  'about.card.text': {
    label: 'Текст карточки о проекте',
    hint: 'Главная, нижний блок слева',
    group: 'home',
    value:
      'Сервер для своих: без доната, приватов и *острых углов*, зато с последствиями. Игроки рассказывают о сделанном завозами, зрители из Telegram ставят плюсы и минусы, а неделя целиком уезжает в архив.',
    maxLength: 400,
    multiline: true,
  },
  'zero.card.title': {
    label: 'Заголовок карточки Zero Season',
    hint: 'Главная, нижний блок справа',
    group: 'home',
    value: 'Zero Season',
    maxLength: 80,
  },
  'zero.card.text': {
    label: 'Текст карточки Zero Season',
    hint: 'Главная, нижний блок справа',
    group: 'home',
    value:
      'Нулевой сезон: короткий состав, еженедельный «Отсчёт», иммунитет и призовой фонд. Проверяем на себе, какие правила *круглые*, а какие пора обтачивать.',
    maxLength: 400,
    multiline: true,
  },

  'empty.trailer.title': {
    label: 'Заглушка трейлера, заголовок',
    hint: 'Главная, пока ссылка на трейлер не задана',
    group: 'home',
    value: 'Трейлер скоро',
    maxLength: 80,
  },
  'empty.trailer.note': {
    label: 'Заглушка трейлера, пояснение',
    hint: 'Главная, строка под заголовком заглушки',
    group: 'home',
    value: 'Монтажёр ещё ищет самый *круглый* кадр.',
    maxLength: 200,
  },
  'empty.week.title': {
    label: 'Заглушка архива, заголовок',
    hint: 'Главная и страница архива, когда недель нет',
    group: 'archive',
    value: 'Архив пока пустой',
    maxLength: 80,
  },
  'empty.week.note': {
    label: 'Заглушка архива, пояснение',
    hint: 'Главная и страница архива',
    group: 'archive',
    value: 'Неделя ещё не успела *округлиться*. Как закончится, положим её сюда целиком.',
    maxLength: 240,
  },
  'empty.players.title': {
    label: 'Заглушка игроков, заголовок',
    hint: 'Главная и страница игроков, когда никого нет',
    group: 'players',
    value: 'Игроков пока нет',
    maxLength: 80,
  },
  'empty.players.note': {
    label: 'Заглушка игроков, пояснение',
    hint: 'Главная и страница игроков',
    group: 'players',
    value: '*Круг* ждёт первых смельчаков. Карточка заводится сама после входа через Minecraft.',
    maxLength: 240,
  },
  'empty.posts.title': {
    label: 'Заглушка ленты, заголовок',
    hint: 'Главная и лента завозов, когда пусто',
    group: 'posts',
    value: 'Завозов пока нет',
    maxLength: 80,
  },
  'empty.posts.note': {
    label: 'Заглушка ленты, пояснение',
    hint: 'Главная и лента завозов',
    group: 'posts',
    value: 'Тут игроки рассказывают, что построили, нашли и с кем договорились.',
    maxLength: 240,
  },

  'footer.tagline': {
    label: 'Строка под логотипом в футере',
    hint: 'Футер, слева',
    group: 'footer',
    value: 'Создаём круг там, где квадрат',
    maxLength: 120,
  },
  'footer.version': {
    label: 'Версия игры в футере',
    hint: 'Футер, под слоганом',
    group: 'footer',
    value: 'Minecraft Java Edition 26.2',
    maxLength: 120,
  },
  'footer.disclaimer': {
    label: 'Правовая строка футера',
    hint: 'Футер, нижняя строка справа',
    group: 'footer',
    value:
      'Сайт не связан с Mojang Studios и Microsoft. Minecraft это товарный знак Mojang Studios. Текстуры и иконки на сайте нарисованы для KRUG.',
    maxLength: 400,
    multiline: true,
  },

  'map.empty.title': {
    label: 'Заглушка карты, заголовок',
    hint: 'Страница карты, пока ссылка не задана',
    group: 'map',
    value: 'Карта ещё не натянута на круг',
    maxLength: 100,
  },
  'map.empty.note': {
    label: 'Заглушка карты, пояснение',
    hint: 'Страница карты, строка под заголовком',
    group: 'map',
    value: 'Как только карта сервера поднимется, она появится прямо здесь.',
    maxLength: 240,
  },

  'points.title': {
    label: 'Заголовок',
    hint: 'Верх страницы /points',
    group: 'points',
    value: 'Баллы: за что KRUG *ставит плюсик*',
    maxLength: 120,
  },
  'points.lead': {
    label: 'Вступление',
    hint: 'Абзац под заголовком',
    group: 'points',
    value: 'KRUG устроен как телешоу: камеры не выключаются, а сюжет пишут игроки. Баллы получает тот, кто делает сервер живым. Не тот, кто тихо копает в углу, а тот, из-за кого у костра есть что обсудить.',
    maxLength: 500,
    multiline: true,
  },
  'points.event.title': {
    label: 'Завозы, заголовок',
    hint: 'Карточка с командным блоком',
    group: 'points',
    value: 'Завозы',
    maxLength: 60,
  },
  'points.event.text': {
    label: 'Завозы, текст',
    hint: 'Карточка с командным блоком',
    group: 'points',
    value: 'События, после которых сервер уже не тот. Собрал людей на рейд, сыграл свадьбу посреди спавна, развязал торговую войну из-за одного алмаза.',
    maxLength: 400,
    multiline: true,
  },
  'points.social.title': {
    label: 'Социальность, заголовок',
    hint: 'Карточка со слизью',
    group: 'points',
    value: 'Социальность',
    maxLength: 60,
  },
  'points.social.text': {
    label: 'Социальность, текст',
    hint: 'Карточка со слизью',
    group: 'points',
    value: 'Знакомишь людей, миришь поссорившихся, собираешь организацию или аккуратно разваливаешь чужую. Сервер держится на связях, а не на стенах.',
    maxLength: 400,
    multiline: true,
  },
  'points.community.title': {
    label: 'Вклад, заголовок',
    hint: 'Карточка с мхом',
    group: 'points',
    value: 'Жизнь KRUG',
    maxLength: 60,
  },
  'points.community.text': {
    label: 'Вклад, текст',
    hint: 'Карточка с мхом',
    group: 'points',
    value: 'Голосовые до утра, арты по серверу, идеи, от которых администрация хватается за голову. Атмосфера сама себя не поддерживает.',
    maxLength: 400,
    multiline: true,
  },
  'points.content.title': {
    label: 'Контент, заголовок',
    hint: 'Карточка со скалк-крикуном',
    group: 'points',
    value: 'Контент',
    maxLength: 60,
  },
  'points.content.text': {
    label: 'Контент, текст',
    hint: 'Карточка со скалк-крикуном',
    group: 'points',
    value: 'Стримы, ролики и шортсы про KRUG. Ценится то, что показывает сервер, а не спам ради спама. Залетевший ролик получает отдельный бонус.',
    maxLength: 400,
    multiline: true,
  },
  'points.scale.title': {
    label: 'Масштаб, заголовок',
    hint: 'Блок под карточками',
    group: 'points',
    value: 'Чем громче, тем *весомее*',
    maxLength: 80,
  },
  'points.scale.text': {
    label: 'Масштаб, текст',
    hint: 'Блок под карточками',
    group: 'points',
    value: 'Маленькая движуха стоит немного. Событие, которое перевернуло неделю, стоит заметно больше. А самые легендарные завозы остаются в истории сезона.',
    maxLength: 400,
    multiline: true,
  },
  'points.campfire.title': {
    label: 'Костёр, заголовок',
    hint: 'Блок с бревном',
    group: 'points',
    value: 'Итоги у *костра*',
    maxLength: 80,
  },
  'points.campfire.text': {
    label: 'Костёр, текст',
    hint: 'Блок с бревном',
    group: 'points',
    value: 'Раз в неделю все собираются на спавне у костра. Там объявляют, кто сколько получил и кто выделился. Приходи, даже если в этот раз пусто: следующая неделя может быть твоей.',
    maxLength: 400,
    multiline: true,
  },
  'points.friends.title': {
    label: 'Друзья, заголовок',
    hint: 'Блок с алмазной рудой',
    group: 'points',
    value: 'Друзья в *круге*',
    maxLength: 80,
  },
  'points.friends.text': {
    label: 'Друзья, текст',
    hint: 'Блок с алмазной рудой',
    group: 'points',
    value: 'Позвал друга, и он прижился? За приглашённых тоже кое-что положено. Подробности расскажем, когда друг окажется в круге.',
    maxLength: 400,
    multiline: true,
  },
  'points.note': {
    label: 'Сноска',
    hint: 'Мелкий текст внизу страницы',
    group: 'points',
    value: 'Точные цифры знает только администрация. Так честнее: играешь ради истории, а не ради таблицы.',
    maxLength: 300,
    multiline: true,
  },
  'points.aboutLink': {
    label: 'Ссылка со страницы «О KRUG»',
    hint: 'Плашка внизу страницы «О KRUG»',
    group: 'points',
    value: 'Как устроены баллы',
    maxLength: 80,
  },

  'nav.posts': {
    label: 'Пункт меню: завозы',
    hint: 'Шапка, мобильное меню и подвал',
    group: 'nav',
    value: 'Завозы',
    maxLength: 80,
  },
  'nav.players': {
    label: 'Пункт меню: игроки',
    hint: 'Шапка, мобильное меню и подвал',
    group: 'nav',
    value: 'Игроки',
    maxLength: 80,
  },
  'nav.map': {
    label: 'Пункт меню: карта',
    hint: 'Шапка, виден когда карта настроена',
    group: 'nav',
    value: 'Карта',
    maxLength: 80,
  },
  'nav.zero': {
    label: 'Пункт меню: Zero Season',
    hint: 'Шапка и подвал',
    group: 'nav',
    value: 'Zero Season',
    maxLength: 80,
  },
  'nav.about': {
    label: 'Пункт меню: о проекте',
    hint: 'Шапка',
    group: 'nav',
    value: 'О KRUG',
    maxLength: 80,
  },
  'nav.join': {
    label: 'Пункт меню: как попасть',
    hint: 'Шапка и подвал',
    group: 'nav',
    value: 'Как попасть',
    maxLength: 80,
  },
  'nav.more': {
    label: 'Кнопка «Ещё»',
    hint: 'Шапка, раскрывает остальные пункты',
    group: 'nav',
    value: 'Ещё',
    maxLength: 80,
  },
  'nav.archive': {
    label: 'Пункт меню: архив',
    hint: 'Меню «Ещё» и подвал',
    group: 'nav',
    value: 'Архив',
    maxLength: 80,
  },
  'nav.media': {
    label: 'Пункт меню: медиа',
    hint: 'Меню «Ещё» и подвал',
    group: 'nav',
    value: 'Медиа',
    maxLength: 80,
  },
  'nav.wiki': {
    label: 'Пункт меню: вики',
    hint: 'Меню «Ещё» и подвал',
    group: 'nav',
    value: 'Вики',
    maxLength: 80,
  },
  'nav.points': {
    label: 'Пункт меню: баллы',
    hint: 'Меню «Ещё»',
    group: 'nav',
    value: 'Баллы',
    maxLength: 80,
  },
  'nav.corner': {
    label: 'Пункт меню: Угол',
    hint: 'Меню «Ещё» и подвал, когда раздел включён',
    group: 'nav',
    value: 'Угол',
    maxLength: 80,
  },
  'nav.team': {
    label: 'Пункт меню: команда',
    hint: 'Меню «Ещё», когда раздел включён',
    group: 'nav',
    value: 'Команда',
    maxLength: 80,
  },
  'nav.login': {
    label: 'Кнопка входа',
    hint: 'Шапка и мобильное меню',
    group: 'nav',
    value: 'Войти',
    maxLength: 80,
  },
  'nav.newPost': {
    label: 'Новый завоз',
    hint: 'Мобильное меню и кнопка с плюсом',
    group: 'nav',
    value: 'Новый завоз',
    maxLength: 80,
  },
  'nav.profile.me': {
    label: 'Меню профиля: кабинет',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Личный кабинет',
    maxLength: 80,
  },
  'nav.profile.page': {
    label: 'Меню профиля: моя страница',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Моя страница',
    maxLength: 80,
  },
  'nav.profile.admin': {
    label: 'Меню профиля: админка',
    hint: 'Видно только администрации',
    group: 'nav',
    value: 'Админка',
    maxLength: 80,
  },
  'nav.profile.logout': {
    label: 'Меню профиля: выйти',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Выйти',
    maxLength: 80,
  },
  'nav.profile.logoutAll': {
    label: 'Меню профиля: выйти везде',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Выйти везде',
    maxLength: 80,
  },
  'nav.profile.player': {
    label: 'Подпись игрока',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Игрок сервера',
    maxLength: 80,
  },
  'nav.profile.viewer': {
    label: 'Подпись зрителя',
    hint: 'Выпадающее меню профиля',
    group: 'nav',
    value: 'Зритель · Telegram',
    maxLength: 80,
  },
  'nav.footer.sections': {
    label: 'Подвал: колонка разделов',
    hint: 'Заголовок колонки',
    group: 'footer',
    value: 'Разделы',
    maxLength: 80,
  },
  'nav.footer.project': {
    label: 'Подвал: колонка проекта',
    hint: 'Заголовок колонки',
    group: 'footer',
    value: 'Проект',
    maxLength: 80,
  },
  'nav.footer.about': {
    label: 'Подвал: что такое KRUG',
    hint: 'Ссылка в подвале',
    group: 'footer',
    value: 'Что такое KRUG',
    maxLength: 80,
  },
  'site.title': {
    label: 'Заголовок сайта в поиске',
    hint: 'Вкладка браузера на главной и превью ссылок',
    group: 'nav',
    value: 'KRUG: Создаём круг там, где квадрат',
    maxLength: 105,
  },
  'site.description': {
    label: 'Описание сайта в поиске',
    hint: 'Сниппет в поисковиках и превью ссылок',
    group: 'nav',
    value: 'KRUG: приватный сервер Minecraft Java Edition 26.2. Создаём круг там, где квадрат.',
    maxLength: 246,
  },
  'home.bubble': {
    label: 'Облачко бедрока',
    hint: 'Появляется, если кликнуть по бедроку в круге на главной',
    group: 'home',
    value: 'Что-то грядёт...',
    maxLength: 80,
  },
  'home.trailer.follow': {
    label: 'Кнопка под пустым трейлером',
    hint: 'Главная, пока трейлера нет',
    group: 'home',
    value: 'Следить за новостями',
    maxLength: 80,
  },
  'posts.title': {
    label: 'Заголовок ленты',
    hint: 'Страница /posts и вкладка браузера',
    group: 'posts',
    value: 'Завозы',
    maxLength: 80,
  },
  'posts.description': {
    label: 'Описание ленты для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'posts',
    value: 'Лента завозов сервера KRUG: что игроки сделали на стриме и вне стрима.',
    maxLength: 210,
  },
  'posts.new': {
    label: 'Кнопка нового завоза',
    hint: 'Над лентой, видна игрокам',
    group: 'posts',
    value: 'Новый завоз',
    maxLength: 80,
  },
  'posts.filter.all': {
    label: 'Фильтр: все',
    hint: 'Переключатель меток над лентой',
    group: 'posts',
    value: 'Все',
    maxLength: 80,
  },
  'tag.stream': {
    label: 'Метка «на стриме»',
    hint: 'Фильтр ленты, карточки завозов, форма',
    group: 'posts',
    value: 'На стриме',
    maxLength: 80,
  },
  'tag.offstream': {
    label: 'Метка «вне стрима»',
    hint: 'Фильтр ленты, карточки завозов, форма',
    group: 'posts',
    value: 'Вне стрима',
    maxLength: 80,
  },
  'posts.emptyTag.title': {
    label: 'Пусто по метке: заголовок',
    hint: 'Лента, когда по выбранной метке ничего нет',
    group: 'posts',
    value: 'С этой меткой пусто',
    maxLength: 80,
  },
  'posts.emptyTag.note': {
    label: 'Пусто по метке: текст',
    hint: 'Лента, когда по выбранной метке ничего нет',
    group: 'posts',
    value: 'С этой меткой ещё ничего не выкладывали. Загляни в общую ленту.',
    maxLength: 189,
  },
  'posts.emptyTag.action': {
    label: 'Пусто по метке: кнопка',
    hint: 'Лента, когда по выбранной метке ничего нет',
    group: 'posts',
    value: 'Вся лента',
    maxLength: 80,
  },
  'posts.prev': {
    label: 'Кнопка «назад»',
    hint: 'Листалка ленты',
    group: 'posts',
    value: 'Назад',
    maxLength: 80,
  },
  'posts.next': {
    label: 'Кнопка «дальше»',
    hint: 'Листалка ленты',
    group: 'posts',
    value: 'Дальше',
    maxLength: 80,
  },
  'post.top': {
    label: 'Значок топа',
    hint: 'Карточка завоза с рейтингом выше 10 за сутки',
    group: 'post',
    value: 'ТОП ЗАВОЗ',
    maxLength: 80,
  },
  'post.pinned': {
    label: 'Метка закреплённого',
    hint: 'Карточка закреплённого завоза',
    group: 'post',
    value: 'Закреплено',
    maxLength: 80,
  },
  'post.open': {
    label: 'Кнопка открыть',
    hint: 'Карточка завоза',
    group: 'post',
    value: 'Открыть',
    maxLength: 80,
  },
  'post.edited': {
    label: 'Пометка правки',
    hint: 'Карточка изменённого завоза, дальше идёт время',
    group: 'post',
    value: 'изменено',
    maxLength: 80,
  },
  'post.back': {
    label: 'Ссылка назад',
    hint: 'Страница завоза',
    group: 'post',
    value: '← К ленте',
    maxLength: 80,
  },
  'post.authorAll': {
    label: 'Ссылка на все завозы автора',
    hint: 'Страница завоза. {nick} заменится ником',
    group: 'post',
    value: 'Все завозы {nick}',
    maxLength: 80,
  },
  'post.notFound': {
    label: 'Завоз не найден',
    hint: 'Вкладка браузера для удалённого завоза',
    group: 'post',
    value: 'Завоз не найден',
    maxLength: 80,
  },
  'post.edit': {
    label: 'Кнопка править',
    hint: 'Свой завоз или админ',
    group: 'post',
    value: 'Править',
    maxLength: 80,
  },
  'post.delete': {
    label: 'Кнопка удалить',
    hint: 'Свой завоз или админ',
    group: 'post',
    value: 'Удалить',
    maxLength: 80,
  },
  'post.deleteConfirm': {
    label: 'Подтверждение удаления',
    hint: 'Появляется после первого нажатия',
    group: 'post',
    value: 'Точно удалить',
    maxLength: 80,
  },
  'post.cancel': {
    label: 'Отмена удаления',
    hint: 'Рядом с подтверждением',
    group: 'post',
    value: 'Отмена',
    maxLength: 80,
  },
  'postNew.title': {
    label: 'Заголовок страницы',
    hint: 'Страница нового завоза',
    group: 'postForm',
    value: 'Новый завоз',
    maxLength: 80,
  },
  'postNew.lead': {
    label: 'Подсказка над формой',
    hint: 'Страница нового завоза',
    group: 'postForm',
    value: 'Коротко о сделанном: что произошло, чем закончилось. Метка «На стриме» ставится, если это было в эфире.',
    maxLength: 309,
    multiline: true,
  },
  'postEdit.title': {
    label: 'Заголовок правки',
    hint: 'Страница правки завоза',
    group: 'postForm',
    value: 'Правка завоза',
    maxLength: 80,
  },
  'postForm.titleLabel': {
    label: 'Поле заголовка',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Заголовок',
    maxLength: 80,
  },
  'postForm.titlePlaceholder': {
    label: 'Подсказка в заголовке',
    hint: 'Серый текст в пустом поле',
    group: 'postForm',
    value: 'Что случилось',
    maxLength: 80,
  },
  'postForm.tag': {
    label: 'Поле метки',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Метка',
    maxLength: 80,
  },
  'postForm.body': {
    label: 'Поле текста',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Текст',
    maxLength: 80,
  },
  'postForm.bodyPlaceholder': {
    label: 'Подсказка в тексте',
    hint: 'Серый текст в пустом поле',
    group: 'postForm',
    value: 'Рассказывай. Можно списком, ссылками и **жирным**.',
    maxLength: 150,
  },
  'postForm.attachments': {
    label: 'Поле вложений',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Вложения',
    maxLength: 80,
  },
  'postForm.addFile': {
    label: 'Кнопка добавить файл',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Добавить файл',
    maxLength: 80,
  },
  'postForm.remove': {
    label: 'Кнопка убрать файл',
    hint: 'Возле выбранного файла',
    group: 'postForm',
    value: 'Убрать',
    maxLength: 80,
  },
  'postForm.locked': {
    label: 'Вложения при правке',
    hint: 'Форма правки опубликованного завоза',
    group: 'postForm',
    value: 'Вложения у опубликованного завоза не меняются. Нужна другая картинка или видео, удали завоз и выложи заново.',
    maxLength: 324,
    multiline: true,
  },
  'postForm.publish': {
    label: 'Кнопка опубликовать',
    hint: 'Новый завоз',
    group: 'postForm',
    value: 'Опубликовать',
    maxLength: 80,
  },
  'postForm.save': {
    label: 'Кнопка сохранить',
    hint: 'Правка завоза',
    group: 'postForm',
    value: 'Сохранить',
    maxLength: 80,
  },
  'postForm.cancel': {
    label: 'Кнопка отмены',
    hint: 'Форма завоза',
    group: 'postForm',
    value: 'Отмена',
    maxLength: 80,
  },
  'postForm.editedNote': {
    label: 'Пояснение про пометку',
    hint: 'Правка завоза',
    group: 'postForm',
    value: 'После сохранения внизу появится пометка «изменено».',
    maxLength: 153,
  },
  'votes.guest': {
    label: 'Гость жмёт стрелку',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Голосуют свои. Войди через Telegram, подпишись на паблик и возвращайся круглым.',
    maxLength: 237,
  },
  'votes.player': {
    label: 'Игрок жмёт стрелку',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Оценку ставят зрители, а не игроки. Ты и так внутри круга, твоё дело завозы.',
    maxLength: 228,
  },
  'votes.self': {
    label: 'Голос за свой завоз',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Хм, может, ты ещё и себе плюсик поставишь? За свой завоз голосовать нельзя.',
    maxLength: 225,
  },
  'votes.already': {
    label: 'Голос уже есть',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Голос уже учтён. Передумать нельзя, мы тут без острых углов.',
    maxLength: 180,
  },
  'votes.subscribed': {
    label: 'Подписка нашлась',
    hint: 'После проверки подписки',
    group: 'votes',
    value: 'Подписка на месте. Голосуй на здоровье.',
    maxLength: 117,
  },
  'votes.notSubscribed': {
    label: 'Подписки нет',
    hint: 'После проверки подписки. {channel} заменится каналом',
    group: 'votes',
    value: 'Подписки на {channel} пока не видно. Проверь, что подписался тем же аккаунтом, которым вошёл.',
    maxLength: 279,
    multiline: true,
  },
  'votes.subscribe': {
    label: 'Кнопка подписаться',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Подписаться',
    maxLength: 80,
  },
  'votes.check': {
    label: 'Кнопка проверки',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Я подписался, проверить',
    maxLength: 80,
  },
  'votes.login': {
    label: 'Кнопка входа',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Войти',
    maxLength: 80,
  },
  'votes.ok': {
    label: 'Кнопка закрыть',
    hint: 'Подсказка под стрелками',
    group: 'votes',
    value: 'Понятно',
    maxLength: 80,
  },
  'votes.up': {
    label: 'Стрелка вверх',
    hint: 'Всплывающая подпись',
    group: 'votes',
    value: 'Плюс',
    maxLength: 80,
  },
  'votes.down': {
    label: 'Стрелка вниз',
    hint: 'Всплывающая подпись',
    group: 'votes',
    value: 'Минус',
    maxLength: 80,
  },
  'players.title': {
    label: 'Заголовок',
    hint: 'Страница /players и вкладка браузера',
    group: 'players',
    value: 'Игроки',
    maxLength: 80,
  },
  'players.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'players',
    value: 'Все игроки сервера KRUG: карточки, завозы, даты первого входа.',
    maxLength: 186,
  },
  'players.sort.nickname': {
    label: 'Сортировка по нику',
    hint: 'Переключатель над списком',
    group: 'players',
    value: 'По нику',
    maxLength: 80,
  },
  'players.sort.recent': {
    label: 'Сортировка по входу',
    hint: 'Переключатель над списком',
    group: 'players',
    value: 'По дате входа',
    maxLength: 80,
  },
  'players.sort.posts': {
    label: 'Сортировка по завозам',
    hint: 'Переключатель над списком',
    group: 'players',
    value: 'По завозам',
    maxLength: 80,
  },
  'players.search': {
    label: 'Подсказка поиска',
    hint: 'Серый текст в поле поиска',
    group: 'players',
    value: 'Ник',
    maxLength: 80,
  },
  'players.searchButton': {
    label: 'Кнопка поиска',
    hint: 'Рядом с полем поиска',
    group: 'players',
    value: 'Найти',
    maxLength: 80,
  },
  'players.notFound.title': {
    label: 'Никого не нашли: заголовок',
    hint: 'Пустой поиск',
    group: 'players',
    value: 'Никого не нашли',
    maxLength: 80,
  },
  'players.notFound.note': {
    label: 'Никого не нашли: текст',
    hint: 'Пустой поиск. {query} заменится запросом',
    group: 'players',
    value: 'По запросу «{query}» никого. Проверь ник, может, где-то заехал угол.',
    maxLength: 204,
  },
  'players.showAll': {
    label: 'Кнопка показать всех',
    hint: 'Пустой поиск',
    group: 'players',
    value: 'Показать всех',
    maxLength: 80,
  },
  'players.never': {
    label: 'Ещё не заходил',
    hint: 'Значок на карточке игрока, добавленного заранее',
    group: 'players',
    value: 'ещё не заходил',
    maxLength: 80,
  },
  'player.role': {
    label: 'Подпись под ником',
    hint: 'Страница игрока, одинаковая для всех',
    group: 'player',
    value: 'Игрок',
    maxLength: 80,
  },
  'player.first': {
    label: 'Факт: первый вход',
    hint: 'Страница игрока',
    group: 'player',
    value: 'Первый вход',
    maxLength: 80,
  },
  'player.never': {
    label: 'Ещё не заходил',
    hint: 'Страница игрока, добавленного заранее',
    group: 'player',
    value: 'ещё не заходил',
    maxLength: 80,
  },
  'player.postsCount': {
    label: 'Факт: завозов',
    hint: 'Страница игрока',
    group: 'player',
    value: 'Завозов',
    maxLength: 80,
  },
  'player.channel': {
    label: 'Секция канала',
    hint: 'Страница игрока с Telegram-каналом',
    group: 'player',
    value: 'Канал игрока',
    maxLength: 80,
  },
  'player.about': {
    label: 'Секция об игроке',
    hint: 'Страница игрока с текстом',
    group: 'player',
    value: 'Об игроке',
    maxLength: 80,
  },
  'player.videos': {
    label: 'Секция видео',
    hint: 'Страница игрока с роликами',
    group: 'player',
    value: 'Видео',
    maxLength: 80,
  },
  'player.posts': {
    label: 'Секция завозов',
    hint: 'Страница игрока',
    group: 'player',
    value: 'Завозы',
    maxLength: 80,
  },
  'player.empty.title': {
    label: 'Нет завозов: заголовок',
    hint: 'Страница игрока без завозов',
    group: 'player',
    value: 'Завозов пока нет',
    maxLength: 80,
  },
  'player.empty.note': {
    label: 'Нет завозов: текст',
    hint: 'Страница игрока без завозов',
    group: 'player',
    value: 'Человек ещё ничего не рассказывал. Значит, копит на большой.',
    maxLength: 180,
  },
  'player.notFound': {
    label: 'Игрок не найден',
    hint: 'Вкладка браузера',
    group: 'player',
    value: 'Игрок не найден',
    maxLength: 80,
  },
  'channel.private': {
    label: 'Канал закрыт',
    hint: 'Блок канала, если канал приватный',
    group: 'player',
    value: 'Канал закрытый, ленту Telegram не отдаёт.',
    maxLength: 123,
  },
  'channel.missing': {
    label: 'Канал не найден',
    hint: 'Блок канала',
    group: 'player',
    value: 'Канал не нашёлся, возможно его переименовали.',
    maxLength: 135,
  },
  'channel.down': {
    label: 'Telegram молчит',
    hint: 'Блок канала',
    group: 'player',
    value: 'Telegram сейчас не отвечает. Посты появятся позже.',
    maxLength: 150,
  },
  'channel.open': {
    label: 'Кнопка открыть канал',
    hint: 'Блок канала. {channel} заменится именем',
    group: 'player',
    value: 'Открыть @{channel}',
    maxLength: 80,
  },
  'channel.read': {
    label: 'Ссылка на пост',
    hint: 'Под постом канала',
    group: 'player',
    value: 'Читать в Telegram →',
    maxLength: 80,
  },
  'me.title': {
    label: 'Заголовок',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Личный кабинет',
    maxLength: 80,
  },
  'me.admin': {
    label: 'Кнопка админки',
    hint: 'Видна только администрации',
    group: 'me',
    value: 'Админка',
    maxLength: 80,
  },
  'me.cardNote': {
    label: 'Про карточку',
    hint: 'Под карточкой игрока',
    group: 'me',
    value: 'Карточку ставит администрация. Нужна другая, напиши в Discord.',
    maxLength: 186,
  },
  'me.role.superadmin': {
    label: 'Своя роль: главный',
    hint: 'Видит только сам человек',
    group: 'me',
    value: 'Главный администратор',
    maxLength: 80,
  },
  'me.role.admin': {
    label: 'Своя роль: админ',
    hint: 'Видит только сам человек',
    group: 'me',
    value: 'Администратор',
    maxLength: 80,
  },
  'me.role.player': {
    label: 'Своя роль: игрок',
    hint: 'Видит только сам человек',
    group: 'me',
    value: 'Игрок',
    maxLength: 80,
  },
  'me.first': {
    label: 'Факт: первый вход',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Первый вход',
    maxLength: 80,
  },
  'me.last': {
    label: 'Факт: последний вход',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Последний вход',
    maxLength: 80,
  },
  'me.postsCount': {
    label: 'Факт: завозов',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Завозов',
    maxLength: 80,
  },
  'me.channel': {
    label: 'Секция канала',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Мой Telegram-канал',
    maxLength: 80,
  },
  'me.channel.has': {
    label: 'Канал добавлен',
    hint: 'Над полем канала. {channel} заменится ссылкой',
    group: 'me',
    value: 'В профиле показываются три последних поста канала {channel}.',
    maxLength: 180,
  },
  'me.channel.none': {
    label: 'Канала нет',
    hint: 'Над полем канала',
    group: 'me',
    value: 'Ведёшь канал? Добавь его, и последние посты появятся на твоей странице. Канал должен быть публичным, иначе Telegram не отдаёт ленту.',
    maxLength: 396,
    multiline: true,
  },
  'me.channel.label': {
    label: 'Поле канала',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Ссылка на канал',
    maxLength: 80,
  },
  'me.channel.hint': {
    label: 'Подсказка поля',
    hint: 'Под полем канала',
    group: 'me',
    value: 'Подойдёт любой вид: @name, t.me/name или полная ссылка.',
    maxLength: 165,
  },
  'me.channel.save': {
    label: 'Кнопка сохранить',
    hint: 'Поле канала',
    group: 'me',
    value: 'Сохранить',
    maxLength: 80,
  },
  'me.channel.remove': {
    label: 'Кнопка убрать',
    hint: 'Поле канала',
    group: 'me',
    value: 'Убрать канал',
    maxLength: 80,
  },
  'me.channel.saved': {
    label: 'Канал сохранён',
    hint: 'После сохранения. {channel} заменится именем',
    group: 'me',
    value: 'Канал @{channel} на месте. Последние посты уже в профиле.',
    maxLength: 171,
  },
  'me.channel.removed': {
    label: 'Канал убран',
    hint: 'После удаления',
    group: 'me',
    value: 'Канал убрали из профиля.',
    maxLength: 80,
  },
  'me.sessions': {
    label: 'Секция сессий',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Сессии',
    maxLength: 80,
  },
  'me.logout': {
    label: 'Кнопка выйти',
    hint: 'Секция сессий',
    group: 'me',
    value: 'Выйти',
    maxLength: 80,
  },
  'me.logoutAll': {
    label: 'Кнопка выйти везде',
    hint: 'Секция сессий',
    group: 'me',
    value: 'Выйти на всех устройствах',
    maxLength: 80,
  },
  'me.posts': {
    label: 'Секция завозов',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Мои завозы',
    maxLength: 80,
  },
  'me.newPost': {
    label: 'Кнопка нового завоза',
    hint: 'Личный кабинет',
    group: 'me',
    value: 'Новый завоз',
    maxLength: 80,
  },
  'me.empty.title': {
    label: 'Нет завозов: заголовок',
    hint: 'Кабинет без завозов',
    group: 'me',
    value: 'Тут пока пусто',
    maxLength: 80,
  },
  'me.empty.text': {
    label: 'Нет завозов: текст',
    hint: 'Кабинет без завозов',
    group: 'me',
    value: 'Расскажи, что построил или с кем договорился: завоз попадёт в ленту и в архив недели. Порадуй *круг*.',
    maxLength: 303,
    multiline: true,
  },
  'me.empty.action': {
    label: 'Нет завозов: кнопка',
    hint: 'Кабинет без завозов',
    group: 'me',
    value: 'Написать завоз',
    maxLength: 80,
  },
  'login.title': {
    label: 'Заголовок',
    hint: 'Страница входа',
    group: 'login',
    value: 'Вход',
    maxLength: 80,
  },
  'login.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'login',
    value: 'Вход на сайт KRUG: через сервер Minecraft для игроков или через Telegram для зрителей.',
    maxLength: 258,
  },
  'login.lead': {
    label: 'Вступление',
    hint: 'Под заголовком',
    group: 'login',
    value: 'Входа два, и они разные. Игрок заходит прямо из игры: сайт сам подтянет ник и скин. Зритель заходит через Telegram, и только так засчитываются голоса за завозы. Выбирай, кто ты в нашем *круге*.',
    maxLength: 579,
    multiline: true,
  },
  'login.mc.kicker': {
    label: 'Minecraft: надпись сверху',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Вариант А',
    maxLength: 80,
  },
  'login.mc.title': {
    label: 'Minecraft: заголовок',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Через сервер Minecraft',
    maxLength: 80,
  },
  'login.mc.text': {
    label: 'Minecraft: текст',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Для игроков KRUG. Аккаунт на сайте привяжется к твоему нику и скину, карточка заведётся сама.',
    maxLength: 279,
    multiline: true,
  },
  'login.mc.getCode': {
    label: 'Кнопка получить код',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Получить код',
    maxLength: 80,
  },
  'login.mc.how1': {
    label: 'Шаг 1 до кода',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Нажми кнопку, сайт покажет код.',
    maxLength: 93,
  },
  'login.mc.how2': {
    label: 'Шаг 2 до кода',
    hint: 'Левая карточка',
    group: 'login',
    value: 'В игре напиши `/krug login КОД`.',
    maxLength: 96,
  },
  'login.mc.how3': {
    label: 'Шаг 3 до кода',
    hint: 'Левая карточка',
    group: 'login',
    value: 'Вкладка войдёт сама.',
    maxLength: 80,
  },
  'login.mc.step1': {
    label: 'Шаг 1 с кодом',
    hint: 'Когда код уже выдан',
    group: 'login',
    value: 'Зайди на сервер.',
    maxLength: 80,
  },
  'login.mc.step2': {
    label: 'Шаг 2 с кодом',
    hint: 'Когда код уже выдан',
    group: 'login',
    value: 'Напиши в чат команду:',
    maxLength: 80,
  },
  'login.mc.copy': {
    label: 'Кнопка копировать',
    hint: 'Возле команды',
    group: 'login',
    value: 'Копировать',
    maxLength: 80,
  },
  'login.mc.copied': {
    label: 'Скопировано',
    hint: 'После копирования',
    group: 'login',
    value: 'Скопировано',
    maxLength: 80,
  },
  'login.mc.waiting': {
    label: 'Ожидание игры',
    hint: 'Пока код жив, дальше идёт таймер',
    group: 'login',
    value: 'Жду тебя в игре.',
    maxLength: 80,
  },
  'login.mc.otherCode': {
    label: 'Кнопка другой код',
    hint: 'Когда код уже выдан',
    group: 'login',
    value: 'Другой код',
    maxLength: 80,
  },
  'login.tg.kicker': {
    label: 'Telegram: надпись сверху',
    hint: 'Правая карточка',
    group: 'login',
    value: 'Вариант Б',
    maxLength: 80,
  },
  'login.tg.title': {
    label: 'Telegram: заголовок',
    hint: 'Правая карточка',
    group: 'login',
    value: 'Через Telegram',
    maxLength: 80,
  },
  'login.tg.text': {
    label: 'Telegram: текст',
    hint: 'Правая карточка. {channel} заменится каналом',
    group: 'login',
    value: 'Для зрителей. Нужен, чтобы голосовать за завозы: голос засчитывается подписчикам {channel}. Никакой *душниловки*, две кнопки и всё.',
    maxLength: 393,
    multiline: true,
  },
  'login.tg.step1': {
    label: 'Шаг 1',
    hint: 'Правая карточка',
    group: 'login',
    value: 'Нажми кнопку, откроется бот.',
    maxLength: 84,
  },
  'login.tg.step2': {
    label: 'Шаг 2',
    hint: 'Правая карточка',
    group: 'login',
    value: 'В боте нажми «Подтвердить вход».',
    maxLength: 96,
  },
  'login.tg.step3': {
    label: 'Шаг 3',
    hint: 'Правая карточка',
    group: 'login',
    value: 'Вкладка войдёт сама.',
    maxLength: 80,
  },
  'login.tg.button': {
    label: 'Кнопка входа',
    hint: 'Правая карточка',
    group: 'login',
    value: 'Войти через Telegram',
    maxLength: 80,
  },
  'login.tg.waiting': {
    label: 'Ожидание бота',
    hint: 'После нажатия, дальше идёт таймер',
    group: 'login',
    value: 'Жду подтверждения в боте.',
    maxLength: 80,
  },
  'login.tg.reopen': {
    label: 'Кнопка открыть бота',
    hint: 'После нажатия',
    group: 'login',
    value: 'Открыть бота ещё раз',
    maxLength: 80,
  },
  'login.tg.hint': {
    label: 'Подсказка ожидания',
    hint: 'После нажатия',
    group: 'login',
    value: 'В боте нажми «Подтвердить вход», вкладка войдёт сама.',
    maxLength: 159,
  },
  'login.done': {
    label: 'Вход удался',
    hint: 'Перед переходом в кабинет',
    group: 'login',
    value: 'Готово, заходим.',
    maxLength: 80,
  },
  'login.err.expired': {
    label: 'Ошибка: код истёк',
    hint: 'Под карточками входа',
    group: 'login',
    value: 'Код протух. Возьми новый и попробуй снова.',
    maxLength: 126,
  },
  'login.err.browser': {
    label: 'Ошибка: другой браузер',
    hint: 'Под карточками входа',
    group: 'login',
    value: 'Код открыт не в том браузере. Начни вход там же, где нажимал кнопку.',
    maxLength: 204,
  },
  'login.err.bot': {
    label: 'Ошибка: бот молчит',
    hint: 'Под карточками входа',
    group: 'login',
    value: 'Связь с ботом пошла квадратно. Попробуй через минуту.',
    maxLength: 159,
  },
  'login.err.copy': {
    label: 'Ошибка копирования',
    hint: 'Если браузер не дал скопировать',
    group: 'login',
    value: 'Браузер не дал скопировать. Ничего, набери команду руками.',
    maxLength: 174,
  },
  'archive.title': {
    label: 'Заголовок',
    hint: 'Страница /archive и вкладка браузера',
    group: 'archive',
    value: 'Архив',
    maxLength: 80,
  },
  'archive.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'archive',
    value: 'Архив сервера KRUG по неделям: постройки, арты, видео и жизнь сервера.',
    maxLength: 210,
  },
  'archive.filter.all': {
    label: 'Фильтр: всё',
    hint: 'Переключатель типов',
    group: 'archive',
    value: 'Всё',
    maxLength: 80,
  },
  'archive.kind.build': {
    label: 'Тип записи: постройка',
    hint: 'Подпись записи в архиве',
    group: 'archive',
    value: 'Постройка',
    maxLength: 80,
  },
  'archive.kind.art': {
    label: 'Тип записи: арт',
    hint: 'Подпись записи в архиве',
    group: 'archive',
    value: 'Арт',
    maxLength: 80,
  },
  'archive.kind.video': {
    label: 'Тип записи: видео',
    hint: 'Подпись записи в архиве',
    group: 'archive',
    value: 'Видео',
    maxLength: 80,
  },
  'archive.kind.post': {
    label: 'Тип записи: завоз',
    hint: 'Подпись записи в архиве',
    group: 'archive',
    value: 'Завоз',
    maxLength: 80,
  },
  'archive.kind.life': {
    label: 'Тип записи: жизнь сервера',
    hint: 'Подпись записи в архиве',
    group: 'archive',
    value: 'Жизнь сервера',
    maxLength: 80,
  },
  'archive.filter.build': {
    label: 'Фильтр: постройки',
    hint: 'Переключатель типов в архиве',
    group: 'archive',
    value: 'Постройки',
    maxLength: 80,
  },
  'archive.filter.art': {
    label: 'Фильтр: арты',
    hint: 'Переключатель типов в архиве',
    group: 'archive',
    value: 'Арты',
    maxLength: 80,
  },
  'archive.filter.video': {
    label: 'Фильтр: видео',
    hint: 'Переключатель типов в архиве',
    group: 'archive',
    value: 'Видео',
    maxLength: 80,
  },
  'archive.filter.life': {
    label: 'Фильтр: жизнь',
    hint: 'Переключатель типов в архиве',
    group: 'archive',
    value: 'Жизнь',
    maxLength: 80,
  },
  'archive.perWeek': {
    label: 'Подпись счётчика',
    hint: 'Последняя неделя, после числа записей',
    group: 'archive',
    value: 'за неделю',
    maxLength: 80,
  },
  'archive.open': {
    label: 'Кнопка открыть неделю',
    hint: 'Последняя неделя',
    group: 'archive',
    value: 'Открыть неделю',
    maxLength: 80,
  },
  'archive.weeks': {
    label: 'Секция недель',
    hint: 'Архив',
    group: 'archive',
    value: 'Все недели',
    maxLength: 80,
  },
  'archive.all': {
    label: 'Секция всех записей',
    hint: 'Архив',
    group: 'archive',
    value: 'Всё подряд',
    maxLength: 80,
  },
  'archive.week': {
    label: 'Слово «неделя»',
    hint: 'Подписи записей, дальше номер',
    group: 'archive',
    value: 'неделя',
    maxLength: 80,
  },
  'archive.draft': {
    label: 'Метка черновика',
    hint: 'Видна только администрации',
    group: 'archive',
    value: 'черновик',
    maxLength: 80,
  },
  'archive.emptyTag.title': {
    label: 'Пусто по типу: заголовок',
    hint: 'Фильтр без записей',
    group: 'archive',
    value: 'С этой меткой пусто',
    maxLength: 80,
  },
  'archive.emptyTag.note': {
    label: 'Пусто по типу: текст',
    hint: 'Фильтр без записей',
    group: 'archive',
    value: 'Выбери другой тип записей или открой архив целиком.',
    maxLength: 153,
  },
  'archive.emptyTag.action': {
    label: 'Пусто по типу: кнопка',
    hint: 'Фильтр без записей',
    group: 'archive',
    value: 'Весь архив',
    maxLength: 80,
  },
  'archiveWeek.back': {
    label: 'Неделя: ссылка назад',
    hint: 'Страница недели',
    group: 'archive',
    value: '← Весь архив',
    maxLength: 80,
  },
  'archiveWeek.notFound': {
    label: 'Неделя не найдена',
    hint: 'Вкладка браузера',
    group: 'archive',
    value: 'Неделя не найдена',
    maxLength: 80,
  },
  'archiveWeek.draft': {
    label: 'Неделя: черновик',
    hint: 'Видно только администрации',
    group: 'archive',
    value: 'черновик, виден только админам',
    maxLength: 90,
  },
  'archiveWeek.empty': {
    label: 'Неделя пустая',
    hint: 'Страница недели без записей',
    group: 'archive',
    value: 'В этой неделе пока пусто.',
    maxLength: 80,
  },
  'archiveWeek.videos': {
    label: 'Неделя: видео',
    hint: 'Секция на странице недели',
    group: 'archive',
    value: 'Видео недели',
    maxLength: 80,
  },
  'media.title': {
    label: 'Заголовок',
    hint: 'Страница /media и вкладка браузера',
    group: 'media',
    value: 'Медиа',
    maxLength: 80,
  },
  'media.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'media',
    value: 'Видео по проекту KRUG: ролики участников, нарезки и записи событий.',
    maxLength: 201,
  },
  'media.all': {
    label: 'Фильтр: все',
    hint: 'Переключатель недель',
    group: 'media',
    value: 'Все',
    maxLength: 80,
  },
  'media.empty.title': {
    label: 'Пусто: заголовок',
    hint: 'Пока видео нет',
    group: 'media',
    value: 'Видео пока нет',
    maxLength: 80,
  },
  'media.empty.note': {
    label: 'Пусто: текст',
    hint: 'Пока видео нет',
    group: 'media',
    value: 'Отдел медиа монтирует. Как только выйдет первый ролик, он окажется здесь.',
    maxLength: 219,
  },
  'wiki.title': {
    label: 'Заголовок',
    hint: 'Страница /wiki и вкладка браузера',
    group: 'wiki',
    value: 'Вики',
    maxLength: 80,
  },
  'wiki.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'wiki',
    value: 'Вики KRUG: статьи об игроках, событиях и устройстве сервера.',
    maxLength: 180,
  },
  'wiki.edit': {
    label: 'Кнопка править',
    hint: 'Видна администрации',
    group: 'wiki',
    value: 'Править',
    maxLength: 80,
  },
  'wiki.empty': {
    label: 'Статей нет',
    hint: 'Пустая вики',
    group: 'wiki',
    value: 'Статей пока нет.',
    maxLength: 80,
  },
  'wiki.updated': {
    label: 'Подпись обновления',
    hint: 'Список статей, дальше дата',
    group: 'wiki',
    value: 'обновлено',
    maxLength: 80,
  },
  'wiki.draft': {
    label: 'Метка черновика',
    hint: 'Видна только администрации',
    group: 'wiki',
    value: 'черновик',
    maxLength: 80,
  },
  'wiki.notFound': {
    label: 'Статья не найдена',
    hint: 'Вкладка браузера',
    group: 'wiki',
    value: 'Статья не найдена',
    maxLength: 80,
  },
  'map.title': {
    label: 'Заголовок',
    hint: 'Вкладка браузера',
    group: 'map',
    value: 'Карта',
    maxLength: 80,
  },
  'map.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'map',
    value: 'Карта сервера KRUG: смотри, что где построено.',
    maxLength: 138,
  },
  'map.loading': {
    label: 'Загрузка',
    hint: 'Пока карта грузится',
    group: 'map',
    value: 'Загружаем карту',
    maxLength: 80,
  },
  'map.failed.title': {
    label: 'Не открылась: заголовок',
    hint: 'Если карта не ответила за 10 секунд',
    group: 'map',
    value: 'Карта не открылась',
    maxLength: 80,
  },
  'map.failed.note': {
    label: 'Не открылась: текст',
    hint: 'Если карта не ответила за 10 секунд',
    group: 'map',
    value: 'Сервер карты молчит или не разрешает показывать себя внутри сайта. Открой её отдельной вкладкой.',
    maxLength: 288,
    multiline: true,
  },
  'map.failed.button': {
    label: 'Не открылась: кнопка',
    hint: 'Если карта не ответила за 10 секунд',
    group: 'map',
    value: 'Открыть карту в новой вкладке',
    maxLength: 87,
  },
  'points.pageTitle': {
    label: 'Вкладка браузера',
    hint: 'Название страницы в браузере и поиске',
    group: 'points',
    value: 'Баллы',
    maxLength: 80,
  },
  'points.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'points',
    value: 'Как на KRUG получают баллы: завозы, социальность, жизнь сообщества и контент.',
    maxLength: 231,
  },
  'points.zeroLink': {
    label: 'Ссылка на правила',
    hint: 'Внизу страницы',
    group: 'points',
    value: 'Правила Zero Season →',
    maxLength: 80,
  },
  'about.title': {
    label: 'Заголовок',
    hint: 'Страница «Что такое KRUG». Основной текст правится в «Тексты страниц»',
    group: 'about',
    value: 'Что такое KRUG',
    maxLength: 80,
  },
  'about.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'about',
    value: 'KRUG: приватный сервер Minecraft Java Edition 26.2: как он устроен, правила, завозы и архив.',
    maxLength: 276,
    multiline: true,
  },
  'zero.title': {
    label: 'Заголовок',
    hint: 'Страница Zero Season. Основной текст правится в «Тексты страниц»',
    group: 'zero',
    value: 'Zero Season',
    maxLength: 80,
  },
  'zero.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'zero',
    value: 'Zero Season: нулевой сезон KRUG: правила, система баллов, еженедельный «Отсчёт», иммунитет и призовой фонд.',
    maxLength: 321,
    multiline: true,
  },
  'zero.intro': {
    label: 'Вступление',
    hint: 'Под заголовком',
    group: 'zero',
    value: 'Нулевой сезон: короткий состав, жёсткие правила, еженедельное выбывание. Всё, что выдержит проверку, переедет в первый сезон.',
    maxLength: 375,
    multiline: true,
  },
  'join.title': {
    label: 'Заголовок',
    hint: 'Страница «Как попасть». Основной текст правится в «Тексты страниц»',
    group: 'join',
    value: 'Как попасть',
    maxLength: 80,
  },
  'join.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'join',
    value: 'Условия набора на сервер KRUG: требования, заявка и порядок отбора.',
    maxLength: 201,
  },
  'join.open': {
    label: 'Набор открыт',
    hint: 'Плашка над текстом',
    group: 'join',
    value: 'Набор открыт',
    maxLength: 80,
  },
  'join.closed': {
    label: 'Набор закрыт',
    hint: 'Плашка над текстом',
    group: 'join',
    value: 'Набор закрыт',
    maxLength: 80,
  },
  'join.status': {
    label: 'Строка статуса',
    hint: 'Плашка над текстом. {status} заменится статусом проекта',
    group: 'join',
    value: 'Статус проекта: {status}.',
    maxLength: 80,
  },
  'join.apply': {
    label: 'Кнопка при открытом наборе',
    hint: 'Плашка над текстом',
    group: 'join',
    value: 'Подать заявку в Discord',
    maxLength: 80,
  },
  'join.follow': {
    label: 'Кнопка при закрытом наборе',
    hint: 'Плашка над текстом',
    group: 'join',
    value: 'Следить в Discord',
    maxLength: 80,
  },
  'corner.title': {
    label: 'Заголовок',
    hint: 'Страница «Угол». Основной текст правится в «Тексты страниц»',
    group: 'corner',
    value: 'Угол',
    maxLength: 80,
  },
  'corner.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'corner',
    value: 'Сабсервер «Угол»: куда попадают выбывшие и те, кто проходит стаж.',
    maxLength: 195,
  },
  'team.title': {
    label: 'Заголовок',
    hint: 'Страница команды',
    group: 'team',
    value: 'Команда',
    maxLength: 80,
  },
  'team.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет в поисковиках',
    group: 'team',
    value: 'Команда проекта KRUG.',
    maxLength: 80,
  },
  'team.empty': {
    label: 'Пустой состав',
    hint: 'Пока команда не заполнена',
    group: 'team',
    value: 'Состав команды пока не заполнен.',
    maxLength: 96,
  },
  'notFound.kicker': {
    label: 'Надпись сверху',
    hint: 'Страница 404',
    group: 'notfound',
    value: 'Ошибка 404',
    maxLength: 80,
  },
  'notFound.title': {
    label: 'Заголовок',
    hint: 'Страница 404 и вкладка браузера',
    group: 'notfound',
    value: 'Тут острый угол',
    maxLength: 80,
  },
  'notFound.text': {
    label: 'Текст',
    hint: 'Страница 404',
    group: 'notfound',
    value: 'Такой страницы нет. Её или снесли, или переименовали, или ты свернул не туда в пещере. Бывает. Давай вернёмся в *круг*.',
    maxLength: 357,
    multiline: true,
  },
  'notFound.home': {
    label: 'Кнопка на главную',
    hint: 'Страница 404',
    group: 'notfound',
    value: 'На главную',
    maxLength: 80,
  },
  'notFound.posts': {
    label: 'Кнопка к завозам',
    hint: 'Страница 404',
    group: 'notfound',
    value: 'К завозам',
    maxLength: 80,
  },
  'home.week.to': {
    label: 'Предлог между датами',
    hint: 'Карточка недели на главной: «1 окт. по 7 окт.»',
    group: 'home',
    value: 'по',
    maxLength: 80,
  },
  'home.week.open': {
    label: 'Кнопка открыть неделю',
    hint: 'Карточка недели на главной',
    group: 'home',
    value: 'Открыть неделю',
    maxLength: 80,
  },
  'home.posts.empty.title': {
    label: 'Нет завозов: заголовок',
    hint: 'Секция завозов на главной',
    group: 'home',
    value: 'Завозов пока нет',
    maxLength: 80,
  },
  'home.posts.empty.note': {
    label: 'Нет завозов: текст',
    hint: 'Секция завозов на главной',
    group: 'home',
    value: 'Тут игроки хвастаются сделанным. Пока тихо, но это ненадолго.',
    maxLength: 183,
  },
  'home.about.more': {
    label: 'Кнопка карточки «О KRUG»',
    hint: 'Внизу главной',
    group: 'home',
    value: 'Подробнее',
    maxLength: 80,
  },
  'home.zero.more': {
    label: 'Кнопка карточки Zero Season',
    hint: 'Внизу главной',
    group: 'home',
    value: 'Читать правила',
    maxLength: 80,
  },
  'player.description': {
    label: 'Описание для поиска',
    hint: 'Сниппет страницы игрока. {nick} заменится ником',
    group: 'player',
    value: 'Страница игрока {nick} на сервере KRUG: карточка, завозы, дата первого входа.',
    maxLength: 231,
  },
  'player.adminEdit': {
    label: 'Кнопка правки',
    hint: 'Видна только администрации',
    group: 'player',
    value: 'Править в админке',
    maxLength: 80,
  },
  'archiveWeek.metaTitle': {
    label: 'Вкладка недели',
    hint: 'Название в браузере. {number} и {title} заменятся',
    group: 'archive',
    value: 'Неделя {number}: {title}',
    maxLength: 80,
  },
  'archiveWeek.metaDescription': {
    label: 'Описание недели для поиска',
    hint: 'Если у недели нет своего описания. {number} заменится номером',
    group: 'archive',
    value: 'Архив недели {number} на сервере KRUG.',
    maxLength: 114,
  },
};

export type TextKey = string;

export type SiteTexts = Record<TextKey, string>;

export const TEXT_KEYS = Object.keys(SITE_TEXTS) as TextKey[];

export function defaultTexts(): SiteTexts {
  const result = {} as SiteTexts;
  for (const key of TEXT_KEYS) result[key] = SITE_TEXTS[key].value;
  return result;
}

/** Подставляет значения вместо {имени} в тексте из настроек. */
export function fillText(text: string, vars: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match,
  );
}
